server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/carwash_users?createDatabaseIfNotExist=true
    username: root
    password: Sumit@56
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
