server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/carwash_auth?createDatabaseIfNotExist=true
    username: root
    password: Sumit@56
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sumitsharma7624@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1

jwt:
  secret: carwashsecretkey123456789012345678901234567890
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
