server:
  port: 8761

spring:
  application:
    name: eureka-server

  cloud:
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
