server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/